# Generated by Django 3.0.2 on 2020-01-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('balance', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='6 Months', max_length=256)),
                ('amount', models.IntegerField(default=5000.0)),
                ('annual_rate', models.FloatField(default=0.15)),
                ('currency', models.CharField(default='$ Americian Dolar', max_length=256)),
                ('status', models.CharField(choices=[('funded', 'Fundded'), ('completed', 'Completed')], max_length=256, null=True)),
                ('total_money', models.IntegerField(default=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.Brrower')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.Investor')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
            ],
        ),
    ]
