# Generated by Django 3.0.2 on 2020-01-19 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='total',
            new_name='total_money',
        ),
        migrations.AddField(
            model_name='loan',
            name='annual_rate',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brrower',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
