# Generated by Django 3.0.2 on 2020-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20200119_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('funded', 'Fundded'), ('completed', 'Completed')], max_length=256, null=True),
        ),
    ]
