# Generated by Django 3.0.2 on 2020-01-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20200117_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total',
            field=models.IntegerField(default=5750),
        ),
    ]
